project_id = "hobzfmqnnztjyrtjspol"

[functions.content]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.health]
verify_jwt = true

[functions.admin-create-student]
verify_jwt = true

[functions.scan-questions]
verify_jwt = true
